### ISSUE TITLE
Simplify the calcDriver pipeline

### ISSUE THREAD

**Issue by johanneskoch94** [pik-piam/mrdrivers#84]
perhaps we don't need all/any the calcPast and calcFuture functions... instead, use non-madrat functions (with activated caching somehow?) and pass the driver as argument...

**Comment by tscheypidi** [comment]
As I just saw this entry: There is a method to include non-madrat functions in the caching. Just for the case that you are not aware of it I just wanted to highlight it. You have to explicitly mention in your code which functions should be monitored, but then they should be fully considered in the caching. You can find an example here:

https://github.com/pik-piam/madrat/blob/master/R/convertTau.R#L14

(note: if you monitor a function that means that changes in the code of the function would get noticed by the caching. It won't notice if the output of a function differs because it either calls another function which is not monitored and changed or because it was run with different inputs)

**Comment by johanneskoch94** [comment]
Thanks, Jan! I should have been more specific, what I'm actually looking for is a way to have the results of non-madrat functions be cached, not just monitored. Is there a way to do that?

**Comment by tscheypidi** [comment]
ah ok, sorry. Caching of function outputs in madrat indeed only works for madrat-based functions.
