### ISSUE TITLE
2005 → 2017 conversion missing for per-capita GDP figures in James and James2019

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/mrdrivers#91]

**Comment by johanneskoch94** [comment]
Do you need the James2019 dataset outside mrdrivers? Because I removed it (it stemming from an email without references) in #89 while also adding the conversion of the James dataset. In general the use of the James dataset in scenario construction should now be much clearer.

Also, the missing conversion almost exclusively affects the scenarios pre-1990.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> Do you need the James2019 dataset outside mrdrivers?

I do not.  But somebody does.

> Because I removed it (it stemming from an email without references) in #89 while also adding the conversion of the James dataset.

MAgPIE will not be pleased …

> Also, the missing conversion almost exclusively affects the scenarios pre-1990.

So does the conversion of historic GDP figures.  And both are used for regressing on historical steel stocks, so converting only one lead to https://github.com/remindmodel/development_issues/issues/354#issue-2550290037, section 3.

**Comment by johanneskoch94** [comment]
> I do not. But somebody does.

I addressed this ;)

>MAgPIE will not be pleased …

Do you know who exactly I could ask for a review on this? 

Can I mark this issue as being resolved with the pending PR? (See line 36 of the new file https://github.com/pik-piam/mrdrivers/pull/89/files#diff-1ab8d30b1395265fc89a6c5c3b33da2bef8a94c5088218f91fd79f0f5919e3a5 )
